version: '3.8'

services:
  # for VPN
  # gluetun:
  #   image: qmcgaw/gluetun
  #   cap_add:
  #     - NET_ADMIN
  #   environment:
  #     - VPN_SERVICE_PROVIDER=mullvad
  #     - VPN_TYPE=openvpn
  #     - OPENVPN_USER=9929775807838938
  #     - SERVER_CITIES=Prague
  #   volumes:
  #     - /gluetun:/gluetun

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=art_db
      - POSTGRES_USER=art_db_user
      - POSTGRES_PASSWORD=art_db_user-password
    ports:
      - '5432:5432'

  # web:
  #   build: .
  #   command: python manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - .:/code
  #   ports:
  #     - 8000:8000
  #   environment:
  #     - DB_HOST=db
  #     - DB_NAME=art_db
  #     - DB_USER=art_db_user
  #     - DB_PASS=art_db_user
  #   depends_on:
  #     - db

volumes:
  postgres_data:
